version: "3.7"
services:
  api:
    restart: always
    image: "victor22junio/tfg-backend:latest"
    env_file:
      - backend.env
    ports:
      - "3020:3020"
    networks:
      - backend
  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: verysecret
    networks:
      - backend
    volumes:
      - mongo_data:/data/db
  frontend:
    image: "victor22junio/tfg-frontend:latest"
    restart: always
    ports:
      - "3000:3000"
networks:
  backend:
    driver: bridge

volumes:
  mongo_data:
    driver: local